// Mock data for development
// This will be replaced by Supabase queries

import type { Product, Category, Service, Promotion, FAQ, ContactInfo, SiteContent, NavItem } from './types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Útiles Escolares',
    slug: 'utiles-escolares',
    icon: '📚',
    description: 'Todo lo que necesitas para el colegio: cuadernos, lápices, mochilas y más.',
    gallery: [
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=600&h=400&fit=crop',
    ],
    order: 1,
    isActive: true,
  },
  {
    id: '2',
    name: 'Papelería',
    slug: 'papeleria',
    icon: '📝',
    description: 'Hojas, cuadernos, agendas, post-its y todo tipo de papelería.',
    gallery: [
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1568702846914-96b305d2uj16?w=600&h=400&fit=crop',
    ],
    order: 2,
    isActive: true,
  },
  {
    id: '3',
    name: 'Tecnología',
    slug: 'tecnologia',
    icon: '💻',
    description: 'Calculadoras, accesorios de computadora, USB, audifonos y más.',
    gallery: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=600&h=400&fit=crop',
    ],
    order: 3,
    isActive: true,
  },
  {
    id: '4',
    name: 'Arte y Manualidades',
    slug: 'arte-manualidades',
    icon: '🎨',
    description: 'Colores, pinturas, pinceles, cartulinas y materiales para manualidades.',
    gallery: [
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1499892477393-f675706cbe6e?w=600&h=400&fit=crop',
    ],
    order: 4,
    isActive: true,
  },
  {
    id: '5',
    name: 'Oficina',
    slug: 'oficina',
    icon: '🏢',
    description: 'Artículos de oficina: grapadoras, perforadoras, archivadores y más.',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&h=400&fit=crop',
    ],
    order: 5,
    isActive: true,
  },
  {
    id: '6',
    name: 'Juguetería',
    slug: 'jugueteria',
    icon: '🎮',
    description: 'Juguetes educativos, rompecabezas, muñecos y entretenimiento para niños.',
    gallery: [
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1472457897821-70d3819a0e24?w=600&h=400&fit=crop',
    ],
    order: 6,
    isActive: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Mochila Escolar Premium',
    slug: 'mochila-escolar-premium',
    description: 'Mochila ergonómica con múltiples compartimentos, ideal para estudiantes. Material resistente al agua.',
    price: 599,
    salePrice: 449,
    sku: 'MOCH-001',
    category: 'Útiles Escolares',
    categorySlug: 'utiles-escolares',
    stock: 50,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    gallery: [],
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Set de Colores Profesionales',
    slug: 'set-colores-profesionales',
    description: 'Caja de 72 colores de alta pigmentación para artistas y estudiantes.',
    price: 299,
    sku: 'COL-072',
    category: 'Arte y Manualidades',
    categorySlug: 'arte-manualidades',
    stock: 100,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop',
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '3',
    name: 'Cuaderno Universitario Premium',
    slug: 'cuaderno-universitario-premium',
    description: 'Cuaderno de 200 hojas con pasta dura y hojas de alta calidad.',
    price: 89,
    salePrice: 69,
    sku: 'CUAD-200',
    category: 'Papelería',
    categorySlug: 'papeleria',
    stock: 200,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop',
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '4',
    name: 'Calculadora Científica FX',
    slug: 'calculadora-cientifica-fx',
    description: 'Calculadora científica con más de 240 funciones para estudiantes de preparatoria y universidad.',
    price: 450,
    sku: 'CALC-FX',
    category: 'Tecnología',
    categorySlug: 'tecnologia',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=400&fit=crop',
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '5',
    name: 'Kit de Geometría Completo',
    slug: 'kit-geometria-completo',
    description: 'Set completo con compás, escuadras, transportador y regla en estuche.',
    price: 159,
    salePrice: 129,
    sku: 'GEO-KIT',
    category: 'Útiles Escolares',
    categorySlug: 'utiles-escolares',
    stock: 80,
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=400&fit=crop',
    isActive: true,
    isFeatured: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    name: 'Marcadores para Pizarrón',
    slug: 'marcadores-pizarron',
    description: 'Set de 12 marcadores de colores vibrantes para pizarrón blanco.',
    price: 189,
    sku: 'MARC-12',
    category: 'Oficina',
    categorySlug: 'oficina',
    stock: 60,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop',
    isActive: true,
    isFeatured: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Papelería y Útiles Escolares',
    slug: 'papeleria-utiles',
    description: 'Gran variedad de útiles escolares, papelería, cuadernos, lapiceros, folders, mochilas y todo lo necesario para el colegio y oficina.',
    shortDescription: 'Todo para el colegio y oficina',
    icon: 'BookOpen',
    price: 'Variedad de precios',
    isActive: true,
    order: 1,
  },
  {
    id: '2',
    name: 'Soporte Técnico de Computadoras',
    slug: 'soporte-tecnico',
    description: 'Reparación de laptops y PCs, instalación de software, recuperación de datos, mantenimiento preventivo, eliminación de virus y optimización de equipos.',
    shortDescription: 'Reparación y mantenimiento de PCs',
    icon: 'Laptop',
    price: 'Desde S/ 30.00',
    isActive: true,
    order: 2,
  },
  {
    id: '3',
    name: 'Desarrollo Web y Sistemas',
    slug: 'desarrollo-web',
    description: 'Creación de páginas web profesionales, landing pages, tiendas online, sistemas de inventario, facturación y todo tipo de sistemas a medida para tu negocio.',
    shortDescription: 'Páginas web y sistemas a medida',
    icon: 'Code',
    price: 'Cotización personalizada',
    isActive: true,
    order: 3,
  },
  {
    id: '4',
    name: 'Sublimación Personalizada',
    slug: 'sublimacion',
    description: 'Personalización de polos, tazas, gorras, cojines, mousepads y más. Ideal para regalos, eventos corporativos y emprendimientos.',
    shortDescription: 'Polos, tazas, gorras personalizadas',
    icon: 'Palette',
    price: 'Desde S/ 15.00',
    isActive: true,
    order: 4,
  },
  {
    id: '5',
    name: 'Impresiones y Copias',
    slug: 'impresiones',
    description: 'Servicio de impresión en blanco y negro y a color. Copias, escaneos, ploteos y enmicados de alta calidad.',
    shortDescription: 'Impresiones, copias y escaneos',
    icon: 'Printer',
    price: 'Desde S/ 0.20',
    isActive: true,
    order: 5,
  },
  {
    id: '6',
    name: 'Trámites Online',
    slug: 'tramites-online',
    description: 'Te ayudamos con trámites de SUNAT, ATU, RENIEC, SIS, AFP, consultas RUC, constancias, certificados y más trámites del Estado peruano.',
    shortDescription: 'SUNAT, ATU, RENIEC y más',
    icon: 'FileCheck',
    price: 'Desde S/ 5.00',
    isActive: true,
    order: 6,
  },
];

export const mockPromotions: Promotion[] = [
  {
    id: '1',
    title: '¡Regreso a Clases!',
    description: 'Hasta 30% de descuento en útiles escolares seleccionados',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=400&fit=crop',
    discount: 30,
    discountType: 'percentage',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    isActive: true,
  },
  {
    id: '2',
    title: 'Impresiones 2x1',
    description: 'Todos los viernes, llévate el doble de impresiones al mismo precio',
    image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&h=400&fit=crop',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    isActive: true,
  },
  {
    id: '3',
    title: 'Pack Universitario',
    description: 'Cuadernos, plumas y calculadora con 20% de descuento',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=400&fit=crop',
    discount: 20,
    discountType: 'percentage',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    isActive: true,
  },
];

export const mockFAQs: FAQ[] = [
  {
    id: '1',
    question: '¿Cuál es el horario de atención?',
    answer: 'Estamos abiertos de lunes a viernes de 8:00 AM a 8:00 PM, sábados de 9:00 AM a 6:00 PM y domingos de 10:00 AM a 2:00 PM.',
    order: 1,
    isActive: true,
  },
  {
    id: '2',
    question: '¿Hacen entregas a domicilio?',
    answer: 'Sí, realizamos entregas a domicilio en la zona metropolitana. El costo varía según la ubicación y el monto de la compra.',
    order: 2,
    isActive: true,
  },
  {
    id: '3',
    question: '¿Aceptan tarjetas de crédito?',
    answer: 'Aceptamos todas las tarjetas de crédito y débito, así como pagos en efectivo y transferencias bancarias.',
    order: 3,
    isActive: true,
  },
  {
    id: '4',
    question: '¿Tienen servicio de impresión urgente?',
    answer: 'Sí, ofrecemos servicio de impresión express con un cargo adicional. Contáctanos para más información.',
    order: 4,
    isActive: true,
  },
  {
    id: '5',
    question: '¿Puedo hacer pedidos por WhatsApp?',
    answer: '¡Por supuesto! Envíanos un mensaje con tu lista de productos y te cotizamos al instante.',
    order: 5,
    isActive: true,
  },
];

export const mockContactInfo: ContactInfo = {
  phone: '+51 999 999 999',
  whatsapp: '51999999999',
  email: 'contacto@libreriaCHROMA.com',
  address: {
    street: 'Av. Principal #123',
    city: 'Lima',
    state: 'Lima',
    postalCode: '15001',
    country: 'Perú',
  },
  coordinates: {
    lat: -12.0464,
    lng: -77.0428,
  },
  hours: {
    weekdays: '8:00 AM - 8:00 PM',
    saturday: '9:00 AM - 6:00 PM',
    sunday: '10:00 AM - 2:00 PM',
  },
  socialMedia: {
    facebook: 'https://facebook.com/papeleriaCHROMA',
    instagram: 'https://instagram.com/papeleriaCHROMA',
  },
};

export const mockSiteContent: SiteContent = {
  heroTitle: 'Tu Centro de Papelería y Servicios',
  heroSubtitle: 'Útiles escolares, impresiones, sublimación, soporte técnico, desarrollo web y trámites online. Todo lo que necesitas en un solo lugar.',
  heroCTA: 'Ver Productos',
  aboutTitle: 'Más de 10 años sirviendo a nuestra comunidad',
  aboutDescription: 'Somos una papelería multiservicios comprometida con ofrecer productos de calidad y servicios profesionales a precios accesibles en Perú.',
  servicesTitle: 'Nuestros Servicios',
  servicesSubtitle: 'Soluciones completas para estudiantes, profesionales y emprendedores',
  productsTitle: 'Productos Destacados',
  productsSubtitle: 'Descubre nuestra selección de productos de alta calidad',
  promotionsTitle: 'Promociones de Temporada',
  contactTitle: 'Contáctanos',
  contactSubtitle: 'Estamos aquí para ayudarte. ¡Escríbenos por WhatsApp!',
};

export const mockNavItems: NavItem[] = [
  { id: '1', label: 'Inicio', href: '#hero', order: 1, isVisible: true },
  { id: '2', label: 'Categorias', href: '#categorias', order: 2, isVisible: true },
  { id: '3', label: 'Servicios', href: '#servicios', order: 3, isVisible: true },
  { id: '4', label: 'Productos', href: '#productos', order: 4, isVisible: true },
  { id: '6', label: 'Contacto', href: '#contacto', order: 6, isVisible: true },
  { id: '5', label: 'Catálogos', href: '#catalogos', order: 5, isVisible: true },
];
